---
- name: setup IP forwarding for IPv6
  sysctl: >
    name=net.ipv6.conf.all.forwarding
    value={{ '1' if iptables_ip_forward|bool else '0' }}
  tags: configuration

- name: configure init script
  template: >
    src=conf.d/ip6tables.j2
    dest=/etc/conf.d/ip6tables
  tags: configuration

- name: start ip6tables and add to boot runlevel
  service: name=ip6tables enabled=true runlevel=boot state=started
