---
- name: install iptables
  portage: package=net-firewall/iptables
  tags: [packages, install]

- name: create destination directory for rules config
  file: >
    path="{{ iptables_rules_file | dirname }}"
    recurse=true
    state=directory
  tags: install

- name: configure rules
  template: >
    src=rules.iptables.j2
    dest="{{ iptables_rules_file }}"
    validate="{{ iptables_validate_cmd }}"
    owner=root group=root mode=644
  notify:
    - reload iptables
    - reload ip6tables
  tags: config

- name: disable IPv6 on all interfaces
  sysctl: >
    name=net.ipv6.conf.all.disable_ipv6
    value=1
  when: not iptables_ipv6
  tags: config

- include: ipv4.yml

- include: ipv6.yml
  when: iptables_ipv6
